### PR TITLE
Update dependencies for the project

### PR DESCRIPTION
**Pull request by alsedi**
Bump framework versions and grade to the actual state.

### CODE REVIEW

**Review by casvanluijtelaar — APPROVED** [review]
make sure to build our internal project with these changes, verify compatibility.

**Comment by casvanluijtelaar** [comment]
also when merged we need to update the dependabot PRs

**Comment by alsedi** [comment]
> make sure to build our internal project with these changes, verify compatibility.

Yes, did it before PR

**Comment by alsedi** [comment]
Final changes tested also for all architectures

**Review by miksto — APPROVED** [review]

**Review by miksto — APPROVED** [review]

**Pull request merged**
